@startuml
title GET /tests/{test_id}/requests/{request_id}/payload
start

:Request;
note: R1
:**test_id** = Request.Path.test_id;
note: str
:**request_id** = Request.Path.request_id;
note: str
:**svc** = Request.Dependency.svc;
note: src.application.services.test_app_service.TestApplicationService

:Получить сервис svc с помощью зависимости.;
:Вызвать svc.get_request_payload с параметрами test_id и request_id.;
:self._require_test_dir(test_id);
:request_path = os.path.join(self._test_dir(test_id), 'requests', f'{request_id}.json');
if (not os.path.exists(request_path)) then (+)
    :data = await self._storage.read_json(request_path);
else (-)
    end
endif
:service_result = {'test_id': test_id, 'request_id': request_id, 'file_path': request_path, 'payload': data};
:Вернуть результат вызова svc.get_request_payload.;

:Build response\nwith **dict[str, Any]**;
note: R2
:HTTP 200 OK;
stop
@enduml
