@startuml
title GET /api/orders/steam/amount - Получить полную стоимость по сумме зачисления
start

:Request;
note: R1

:**netAmount** = Request.Query.NetAmount;
note
    Сумма зачисления в Steam (RUB)
    из запроса
end note

:**account** = Request.Query.Account;
note: Аккаунт пользователя Steam

#palegreen :**terminal** = retrieve\nby GET /api/h2h/terminals\nfrom WataApi;
note: A1

:**terminalComissionInPercent** = **terminal.rates[0]**;
note: Комиссия Терминала **(в процентах)**

#palegreen :**donateHubRates** = retrieve "Steam rates (USDT->RUB)"\nby GET /api/steam_course\nfrom DonateHub;
note: A2

:**donateHubRateUsdtToRub** = **donateHubRates.USD_RUB**;
note: Курс USDT -> RUB в DonateHub

:**netAmountUsdt** = **netAmount** / **donateHubRateUsdtToRub**;
note: Сумма зачисления в Steam (USDT)

#palegreen :**replenishment** = retrieve\nby GET /api/create_steam_order\nwith: `account` = **account**, `amount` = **netAmountUsdt**\nfrom DonateHub;
note: A3

:**donateHubTotalUsdt** = **replenishment.total**;
note
    Полная стоимость операции в DonateHub в USDT,
    с учетом вычетов на стороне DonateHub
end note

#palegreen :**wataRates** = retrieve "Wata rates (RUB->USDT)"\nby GET /api/h2h/rates\nfrom WataApi;
note: A4

:**wataRateRubToUsdt** = **wataRates.rate**;
note: Курс RUB->USDT в Wata
:**wataComissionRub** = **donateHubTotalUsdt** / **wataRateRubToUsdt** * (**terminalComissionInPercent** / 100);
note
    Комиссия которую берет Wata (RUB),
    за зачисление **netAmountRub**
    на аккаунт в Steam
end note

:**totalAmountRub** = **donateHubTotalUsdt** / **wataRateRubToUsdt** + **wataComissionRub**;
note: Сумма оплаты (RUB)

:Build response\nwith: `amountTotal` = Round(**totalAmountRub**);
note: R2

:HTTP 200 OK;
end

@enduml