@startuml
title GET /api/h2h/rates - Получение курса RUB->USDT из WataApi
start

:Params: no params;

#palegreen :GET /api/h2h/rates;

:**Response**;
note: A4.R2

if (**Response.Code** = HTTP 200?) then (+)
    :**Response.Body**;
    stop
endif

:HTTP 400 BadRequest;
end

@enduml