@startuml
title GET /api/h2h/links/{id} - Получение ссылки на оплату из WataApi
start

:Params: **id**;
note
    Идентификатор ссылки
    на оплату в Wata API
end note

#palegreen :GET /api/h2h/links/{id}\nwith path params: `id` = **id**;

:**Response**;
note: A3.R2

if (**Response.Code** = HTTP 200?) then (+)
    :**paymentLink** = {\n  successRedirectUrl: **Response.Body.successRedirectUrl**,\n  failRedirectUrl: **Response.Body.failRedirectUrl** \n};
    
    :**paymentLink**;
    stop
endif

:**paymentLink** = {\n  successRedirectUrl: null,\n  failRedirectUrl: null \n};

:**paymentLink**;
stop

@enduml