@startuml
title POST api/orders/steam - Создать ссылку на оплату
start

:Request;
note: R1

:**netAmount** = Request.Body.netAmount;
note
    Сумма зачисления в Steam (RUB)
    из запроса
end note

:**amount** = Request.Body.amount;
note
    Сумма оплаты (RUB)
    из запроса
end note

:**account** = Request.Body.account;
note: Аккаунт пользователя Steam

:**orderId** = Request.Body.orderId;
note
    Идентификатор заказа
    в системе Пользователя
end note

:**description** = Request.Body.description;

:**successRedirectUrl** = Request.Body.successRedirectUrl;

:**failRedirectUrl** = Request.Body.failRedirectUrl;

:**Config** = application config;

#palegreen :**terminal** = retrieve\nby GET /api/h2h/terminals\nfrom WataApi;
note: A1

:**terminalComissionInPercent** = **terminal.rates[0]**;
note: Комиссия Терминала **(в процентах)**

:**terminalPublicId** =  **terminal.publicId**;
note: Сквозной идентификатор

partition Проверка наличия заказа в БД {
    if (find in DB `Orders` where ( `OrderId` = **orderId** AND `PublicId` = **terminalPublicId** )) then (+)
        :HTTP 400 BadRequest\nwith error code **Config.ErrorCodes.AlreadyExists**;
        note
            Заказ уже существует
            ====
            DigitalGoods:ORD_1002
        end note
        end
    endif
}

#palegreen :**donateHubRates** = retrieve "Steam rates (USDT->RUB)"\nby GET /api/steam_course\nfrom DonateHub;
note: A2

:**donateHubRateUsdtToRub** = **donateHubRates.USD_RUB**;
note: Курс USDT -> RUB в DonateHub

:**netAmountUsdt** = **netAmount** / **donateHubRateUsdtToRub**;
note: Сумма зачисления в Steam (USDT)

#palegreen :**replenishment** = retrieve\nby GET /api/create_steam_order\nwith: `account` = **account**, `amount` = **netAmountUsdt**\nfrom DonateHub;
note: A3

:**donateHubCustomId** = **replenishment.custom_id**;

:**donateHubTotalUsdt** = **replenishment.total**;
note
    Полная стоимость операции в DonateHub в USDT,
    с учетом вычетов на стороне DonateHub
end note

#palegreen :**wataRates** = retrieve "Wata rates (RUB->USDT)"\nby GET /api/h2h/rates\nfrom WataApi;
note: A4

:**wataRateRubToUsdt** = **wataRates.rate**;
note: Курс RUB->USDT в Wata

:**goodPriceRub** = **donateHubTotalUsdt** / **wataRateRubToUsdt**;
note: Стоимость ЦТ (RUB)

:**wataComissionRub** = **donateHubTotalUsdt** / **wataRateRubToUsdt** * (**terminalComissionInPercent** / 100);
note
    Комиссия которую берет Wata (RUB),
    за зачисление **netAmountRub**
    на аккаунт в Steam
end note

:**totalAmountRub** = **goodPriceRub** + **wataComissionRub**;
note
    Сумма оплаты (RUB), заново расчитанная
    из **netAmount** в запросе
end note

if (**totalAmountRub** > **amount**) then (+)
    :HTTP 400 BadRequest\nwith error code **Config.ErrorCodes.OrderAmountTooLow**;
    note
        Ошибка платежа, обратитесь в магазин
        ====
        DigitalGoods:ORD_1003
    end note
    end
endif

#palegreen :**paymentLink** = create "Payment link"\nby POST /api/h2h/links\nwith: `amount` = Round(**amount**), `goodPrice` = Round(**goodPriceRub**), `description` = **description**, `orderId` = **orderId**\n`successRedirectUrl` = **successRedirectUrl**, `failRedirectUrl` = **failRedirectUrl**\non WataApi;
note: A5

:**steamDetails** = { DonateHubCustomId: **donateHubCustomId** };

partition Создать заказ в БД {
    :create in DB `Orders` with ( `Details` = **steamDetails**,
    `OrderId` = **orderId**, `PublicId` = **terminalPublicId**, `Status` = **Config.DonateHubOrderStatuses.IN_QUEUE**,
    `Amount` = **amount**, `GoodPrice` = **goodPriceRub**, `PaymentLinkId` = **paymentLink.id**,
    `Type` = **Config.DigitalGoodsOrderType.Steam** );
    note
        Комбинация **orderId** и **terminalPublicId**
        обеспечивает идентификацию заказа
        (неповторяемость)
    end note
}

:Build response\nwith `orderId` = **orderId**, `amount` = Round(**amount**), `paymentLink` = **paymentLink.url**,\n`successRedirectUrl` = **successRedirectUrl**, `failRedirectUrl` = **failRedirectUrl**;
note: R2

:HTTP 200 OK;

end

@enduml