@startuml
title GET /api/game/{id} - Получение информация об игре из DonateHub API
start

:Params: **id**;
note
    Идентификатор игры
    в DonateHub
end note

#palegreen :GET /api/game/{id}\nwith path params: `id` = **id**;

:**Response**;
note: A3.R2

if (**Response.Code** = HTTP 200?) then (+)
    :**Response.Body**;
    stop
endif

if (**Response.Code** = HTTP 401?) then (+)
    :HTTP 401 Unauthorized;
    end
endif

if (**Response.Code** = HTTP 403?) then (+)
    :HTTP 403 Forbidden;
    end
endif

:HTTP 400 BadRequest;
end

@enduml