@startuml
title GET /api/topup/{id} - Получение информации по игре и её позициям
start

:Request;
note: R1

:**gameId** = Request.Params.id;
note
    Идентификатор игры в DonateHub
end note

#palegreen :**terminal** = retrieve\nby GET /api/h2h/terminals\nfrom WataApi;
note: A1

:**terminalComissionInPercent** = **terminal.rates[0]**;
note: Комиссия Терминала **(в процентах)**

#palegreen :**wataRates** = retrieve "Wata rates (RUB->USDT)"\nby GET /api/h2h/rates\nfrom WataApi;
note: A2

:**wataRateRubToUsdt** = **wataRates.rate**;
note: Курс RUB->USDT в Wata

#palegreen :**donateHubGame** = retrieve\nby GET /api/game/{id}\nwith `id` = **gameId**\nfrom DonateHub;
note: A3

#palegreen :**topUpPositions** = transform (**donateHubGame.positions**)\nusing: `gameId` = **donateHubGame.id**, `gameName` =  **donateHubGame.name**,\n**wataRateRubToUsdt**, **terminalComissionInPercent**;
note
    A4, M1, C1
    Маппинг позиций
    list<DonateHubPostionDto> -> list<TopUpPositionDto>
    И перерасчет цены, с учетом комиссии и рейта Wata
end note

:**topUpGame** : TopUpGameDto = map (**donateHubGame**);
note
    M2
    DonateHubGameDto -> TopUpGameDto
end note

:**topUpGame.positions** = **topUpPositions**;
note
    Добавляем список позиций
    в поле `positions`
end note

:Build response\nusing **topUpGame**;
note: R2

:HTTP 200 OK;
end

@enduml