@startuml
title GET /api/topup - Получение списка игр и игровых позиций
start

:Request;

#palegreen :**terminal** = retrieve\nby GET /api/h2h/terminals\nfrom WataApi;
note: A1

:**terminalComissionInPercent** = **terminal.rates[0]**;
note: Комиссия Терминала **(в процентах)**

#palegreen :**wataRates** = retrieve "Wata rates (RUB->USDT)"\nby GET /api/h2h/rates\nfrom WataApi;
note: A4

:**wataRateRubToUsdt** = **wataRates.rate**;
note: Курс RUB->USDT в Wata

#palegreen :**donateHubGames** = retrieve\nby GET /api/game\nfrom DonateHub;
note: A2

#palegreen :**donateHubPositions** = retrieve\nby GET /api/products\nfrom DonateHub;
note: A3

#palegreen :**filteredPositionsGroupedByProductId** = transform (**donateHubPositions**)\ngroup by `product_id`\nfilter by `category` = "Games" AND `price` > 0\nusing: **donateHubGames**;
note
    A5
    list<DonateHubPositionDto> ->
    map<key, list<DonateHubPositionDto>>
end note

#palegreen :**topUpGames** = transform (**donateHubGames**)\nusing: **filteredPositionsGroupedByProductId**,\n**wataRateRubToUsdt**, **terminalComissionInPercent**;
note
    A6, A7, M1, M2, C1
    list<DonateHubGameDto> -> list<TopUpGameDto>
end note



:Build response\nusing **topUpGames**;
note: R2

:HTTP 200 OK;
end

@enduml