@startuml
title GET /api/game - Получение списка игр из DonateHub
start

:Params: no params;

#palegreen :GET /api/game;

:**Response**;
note: A2.R2

if (**Response.Code** = HTTP 200?) then (+)
    :**Response.Body**;
    stop
endif

:HTTP 400 BadRequest;
end

@enduml