@startuml
title POST /api/topup - Создание заказа на покупку игры или игровой позиции
start

:Request;
note: R1

:**orderId** = Request.Body.orderId;
note
    Идентификатор заказа
    в системе Пользователя
end note

:**amount** = Request.Body.amount;
note
    Сумма оплаты (RUB)
    из запроса
end note

:**positionId** = Request.Body.positionId;
note
    Идентификатор позиции игры
end note

:**description** = Request.Body.description;

:**fields** = Request.Body.fields;
note
    Необходимые поля при создании заказа
end note

:**email** = Request.Body.email;

:**successRedirectUrl** = Request.Body.successRedirectUrl;

:**failRedirectUrl** = Request.Body.failRedirectUrl;

:**Config** = application config;

#palegreen :**terminal** = retrieve\nby GET /api/h2h/terminals\nfrom WataApi;
note: A1
    
:**terminalComissionInPercent** = **terminal.rates[0]**;
note: Комиссия Терминала **(в процентах)**

:**terminalPublicId** =  **terminal.publicId**;
note: Сквозной идентификатор

partition Проверка наличия заказа в БД {
    if (find in DB `Orders` where ( `OrderId` = **orderId** AND `PublicId` = **terminalPublicId** )) then (+)
        :HTTP 400 BadRequest\nwith error code **Config.ErrorCodes.AlreadyExists**;
        note
            Заказ уже существует
            ====
            DigitalGoods:ORD_1002
        end note
        end
    endif
}

#palegreen :**donateHubPositions** = retrieve\nby GET /api/products\nfrom DonateHub;
note: A2

:**position** = find in **donateHubPositions** where `position_id` = **positionId**\nAND `category` = **Config.DonatehubCategories.Games**;

if (**position** not found?) then (+)
    :HTTP 400 BadRequest\nwith error code **Config.ErrorCodes.NotFound**;
    note
        Позиция не найдена
        ====
        DigitalGoods:TPP_1001
    end note
    end
endif

#palegreen :**wataRates** = retrieve "Wata rates (RUB->USDT)"\nby GET /api/h2h/rates\nfrom WataApi;
note: A3

:**wataRateRubToUsdt** = **wataRates.rate**;
note: Курс RUB->USDT в Wata

:**wataComissionRub** = **position.price** / **wataRateRubToUsdt** * (**terminalComissionInPercent** / 100);
note
    Комиссия которую берет Wata (RUB),
    за оплату **position.price**
end note

:**goodPriceRub** = **position.price** / **wataRateRubToUsdt**;
note: Стоимость ЦТ (RUB)

:**totalAmountRub** = **goodPriceRub** + **wataComissionRub**;
note
    Сумма оплаты (RUB)
end note

if (**totalAmountRub** > **amount**) then (+)
    :HTTP 400 BadRequest\nwith error code **Config.ErrorCodes.OrderAmountTooLow**;
    note
        Ошибка платежа, обратитесь в магазин
        ====
        DigitalGoods:ORD_1003
    end note
    end
endif

#palegreen :**paymentLink** = create "Payment link"\nby POST /api/h2h/links\nwith: `amount` = Round(**amount**), `goodPrice` = Round(**goodPriceRub**), `description` = **description**, `orderId` = **orderId**\n`successRedirectUrl` = **successRedirectUrl**, `failRedirectUrl` = **failRedirectUrl**\non WataApi;
note: A4

:**topupDetails** = { Email: **email**, PositionId: **position.position_id**\nGameId: **position.product_id**, UserId: **fields.userId**, Server: **fields.server** };

partition Создать заказ в БД {
    :create in DB `Orders` with ( `Details` = **topupDetails**, 
    `OrderId` = **orderId**, `Status` = **Config.DonateHubOrderStatuses.IN_QUEUE**,
    `PublicId` = **terminalPublicId**, `Amount` = **amount**, `GoodPrice` = **goodPriceRub**,
    `PaymentLinkId` = **paymentLink.id**, `Type` = **Config.DigitalGoodsOrderType.TopUp** );
    note
        Комбинация **orderId** и **terminalPublicId**
        обеспечивает идентификацию заказа
        (неповторяемость)
    end note
}

:Build response\nwith `orderId` = **orderId**, `amount` = Round(**amount**), `paymentLink` = **paymentLink.url**,\n`price` = **totalAmountRub**, `userId` = **fields.userId**, `email` = **email**, `server` = **fields.server**,\n`gameId` = **position.product_id**, `successRedirectUrl` = **successRedirectUrl**, `failRedirectUrl` = **failRedirectUrl**;
note: R2

:HTTP 200 OK;

end

@enduml