@startuml
title GET /api/vouchers/services - Получение списка сервисов для кодов пополнений из DonateHub
start

:Params: no params;

#palegreen :GET /api/vouchers/services;

:**Response**;
note: A2.R2

if (**Response.Code** = HTTP 200?) then (+)
    :**Response.Body**;
    stop
endif

:HTTP 400 BadRequest;
end

@enduml