@startuml
title GET /api/vouchers/services - Получение списка сервисов для кодов пополнений
start

:Request;

#palegreen :**terminal** = retrieve\nby GET /api/h2h/terminals\nfrom WataApi;
note: A1

#palegreen :**donateHubServices** = retrieve\nby GET /api/vouchers/services;
note: A2

:Build response\nusing **donateHubServices**;
note: R2

:HTTP 200 OK;
end

@enduml