@startuml
title GET /api/vouchers - Получение списка доступных кодов пополнений сервиса из DonateHub
start

:Params: **serviceId**, **country**;

#palegreen :GET /api/vouchers\nwith query params: `service_id` = **serviceId**, `country` = **country**;

:**Response**;
note: A3.R2

if (**Response.Code** = HTTP 200?) then (+)
    :**Response.Body**;
    stop
endif

if (**Response.Code** = HTTP 401?) then (+)
    :HTTP 401 Unauthorized;
    end
endif

:HTTP 400 BadRequest;
end

@enduml