@startuml
title GET /api/vouchers/order/{id} - Получение информации о купленных кодах пополнений из DonateHub
start

:Params: **id**;
note
    Идентификатор заказа
    в DonateHub
end note

#palegreen :GET /api/vouchers/order/{id}\nwith path params: `id` = **id**;

:**Response**;
note: A4.R2

if (**Response.Code** = HTTP 200?) then (+)
    :**Response.Body**;
    stop
endif

:HTTP 400 BadRequest;
end

@enduml