@startuml
title GET /api/vouchers - Получение списка доступных кодов пополнений
start

:Request;

:**serviceId** = Request.Query.serviceId;
note
    Идентификатор сервиса
end note

:**country** = Request.Query.country;
note
    Страна
end note

#palegreen :**terminal** = retrieve\nby GET /api/h2h/terminals\nfrom WataApi;
note: A1

:**terminalComissionInPercent** = **terminal.rates[0]**;
note: Комиссия Терминала **(в процентах)**

#palegreen :**wataRates** = retrieve "Wata rates (RUB->USDT)"\nby GET /api/h2h/rates\nfrom WataApi;
note: A2

:**wataRateRubToUsdt** = **wataRates.rate**;
note: Курс RUB->USDT в Wata

#palegreen :**donateHubVouchers** = retrieve\nby GET /api/vouchers\nwith: `serviceId` = **serviceId**, `country` = **country**\nfrom DonateHub;
note: A3

:**filteredDonateHubVouchers** = filter **donateHubVouchers**\nwhere `price` > 0;
note
    DonateHub API может вернуть
    позицию с нулевой ценой
    (особенности реализации
    на стороне DonateHub)
end note

:**vouchers** = empty list<VoucherDto>;
note
    Создаем пустой список,
    целевой объект возвращаемый в ответе
end note

repeat :foreach **donateHubVoucher** in **filteredDonateHubVouchers**;
    :**voucher** : VoucherDto = map (**donateHubVoucher**);
    note
        M1
        DonateHubVoucherDto -> VoucherDto
    end note
    
    #palegreen :**totalAmountRub** = calculate(**voucher.price**, **wataRateRubToUsdt**, **terminalComissionInPercent**);
    note: C1
    
    :**voucher.price** = **totalAmountRub**;
    note
        Заменяем цену с учетом комиссии
        в поле `price`
    end note
    
    :add **voucher** into **vouchers**;
repeat while;

:Build response\nusing **vouchers**;
note: R2

:HTTP 200 OK;
end

@enduml