@startuml
title POST /api/vouchers - Создание заказа на покупку кодов пополнений
start

:Request;
note: R1

:**orderId** = Request.Body.orderId;
note
    Идентификатор заказа
    в системе Пользователя
end note

:**amount** = Request.Body.amount;
note
    Сумма оплаты (RUB)
    из запроса
end note

:**voucherId** = Request.Body.voucherId;
note
    Идентификатор кода
    пополнения
end note

:**count** = Request.Body.count;

:**email** = Request.Body.email;

:**description** = Request.Body.description;

:**successRedirectUrl** = Request.Body.successRedirectUrl;

:**failRedirectUrl** = Request.Body.failRedirectUrl;

:**Config** = application config;

#palegreen :**terminal** = retrieve\nby GET /api/h2h/terminals\nfrom WataApi;
note: A1
    
:**terminalComissionInPercent** = **terminal.rates[0]**;
note: Комиссия Терминала **(в процентах)**

:**terminalPublicId** =  **terminal.publicId**;
note: Сквозной идентификатор

partition Проверка наличия заказа в БД {
    if (find in DB `Orders` where ( `OrderId` = **orderId** AND `PublicId` = **terminalPublicId** )) then (+)
        :HTTP 400 BadRequest\nwith error code **Config.ErrorCodes.AlreadyExists**;
        note
            Заказ уже существует
            ====
            DigitalGoods:ORD_1002
        end note
        end
    endif
}

#palegreen :**donateHubPositions** = retrieve\nby GET /api/products\nfrom DonateHub;
note: A2

:**position** = find in **donateHubPositions** where `position_id` = **voucherId**\nAND `category` = **Config.DonatehubCategories.Vouchers**;

if (**position** not found?) then (+)
    :HTTP 400 BadRequest\nwith error code **Config.ErrorCodes.NotFound**;
    note
        Ваучер не найден.
        ====
        DigitalGoods:VCR_1001
    end note
    end
endif

#palegreen :**wataRates** = retrieve "Wata rates (RUB->USDT)"\nby GET /api/h2h/rates\nfrom WataApi;
note: A3

:**wataRateRubToUsdt** = **wataRates.rate**;
note: Курс RUB->USDT в Wata

:**wataComissionRub** = **position.price** / **wataRateRubToUsdt** * (**terminalComissionInPercent** / 100);
note
    Комиссия которую берет Wata (RUB),
    за оплату **position.price**
end note

:**goodPriceRub** = **position.price** / **wataRateRubToUsdt**;
note: Стоимость ЦТ (RUB)

:**totalAmountRub** = **goodPriceRub** + **wataComissionRub**;
note
    Сумма оплаты (RUB)
end note

if (**totalAmountRub** > **amount**) then (+)
    :HTTP 400 BadRequest\nwith error code **Config.ErrorCodes.OrderAmountTooLow**;
    note
        Ошибка платежа, обратитесь в магазин
        ====
        DigitalGoods:ORD_1003
    end note
    end
endif

#palegreen :**paymentLink** = create "Payment link"\nby POST /api/h2h/links\nwith: `amount` = Round(**amount**), `goodPrice` = Round(**goodPriceRub**), `description` = **description**, `orderId` = **orderId**\n`successRedirectUrl` = **successRedirectUrl**, `failRedirectUrl` = **failRedirectUrl**\non WataApi;
note: A4

:**voucherDetails** = { Email: **email**, CodeId: **voucherId**, Count: **count** };

partition Создать заказ в БД {
    :create in DB `Orders` with ( `Details` = **voucherDetails**,
    `OrderId` = **orderId**, `PublicId` = **terminalPublicId**,
    `Status` = **Config.DonateHubOrderStatuses.IN_QUEUE**, `Amount` = **amount**,
    `GoodPrice` = **goodPriceRub**, `PaymentLinkId` = **paymentLink.id**,
    `Type` = **Config.DigitalGoodsOrderType.Voucher** );
    note
        Комбинация **orderId** и **terminalPublicId**
        обеспечивает идентификацию заказа
        (неповторяемость)
    end note
}

:Build response\nwith `orderId` = **orderId**, `amount` = Round(**amount**), `price` = **totalAmountRub**,\n`codeId` = **voucherId**, `count` = **count**, `email` = **email**, `paymentLink` = **paymentLink.url**\n`successRedirectUrl` = **successRedirectUrl**, `failRedirectUrl` = **failRedirectUrl**;
note: R2

:HTTP 200 OK;

end

@enduml