@startuml
title POST /api/create_game_order - Создание заказа на донат в игру в DonateHub
start

:Params: **position**, **fields**;

:**Config** = application config;

:Build request\nwith: `position` = **position**, `fields` = **fields**;
note: A2.R1

#palegreen :POST /api/create_game_order;

:**Response**;
note: A2.R2

if (**Response.Code** = HTTP 200?) then (+)
    :**Response.Body**;
    stop
endif

if (**Response.Code** = HTTP 401?) then (+)
    :HTTP 401 Unauthorized;
    end
endif

if (**Response.Code** = HTTP 400 AND\n**Response.Body.error_message** = **Config.DonatehubErrorsMessages.InsufficientFunds**?) then (+)
    :HTTP 400 BadRequest\nwith error code **Config.ErrorCodes.InsufficientFunds**;
    note
        Недостаточно средств на балансе.
        ====
        DigitalGoods:STM_1004
    end note
    end
endif

:HTTP 400 BadRequest;
end

@enduml